# Generated by Django 3.1.4 on 2020-12-22 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='liked_by',
            field=models.ManyToManyField(related_name='memes_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
