# Generated by Django 3.1.4 on 2020-12-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0004_auto_20201226_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
    ]
