# Generated by Django 3.1.4 on 2020-12-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memes', to='meme.category'),
            preserve_default=False,
        ),
    ]
