# Generated by Django 3.1.4 on 2020-12-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0007_meme_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['-modified']},
        ),
    ]
